# Generated by Django 5.2.8 on 2025-11-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['grade', 'subject'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='questions',
            name='correctAnswer',
            field=models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Explanation for the correct answer', null=True),
        ),
    ]
