# Generated by Django 5.2.8 on 2025-11-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_questions_options_questions_correctanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='explanationVoice',
            field=models.FileField(blank=True, help_text='Audio file with text-to-speech version of the explanation', null=True, upload_to='audio/explanations/'),
        ),
    ]
